program: train.py
method: bayes
metric:
  goal: maximize
  name: correlation
parameters:
  hidden1:
    values: [4, 8, 16, 32, 64, 128, 256, 512, 1024]
  hidden2:
    values: [4, 8, 16, 32, 64, 128, 256, 512, 1024]
  latent_input_dim:
    values: [4, 8, 16, 32, 64, 128, 256, 512, 1024]
  latent_target_dim:
    values: [4, 8, 16, 32, 64, 128, 256, 512, 1024]
  lr:
    values: [1e-4, 5e-4, 1e-3, 5e-3, 1e-2, 5e-2, 1e-1]