program: main.py
method: bayes
metric:
  goal: maximize
  name: best_correlation
parameters:
  dropout:
    values: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  hidden1:
    distribution: uniform
    min: 3
    max: 10
  hidden2:
    distribution: uniform
    min: 3
    max: 10
  hidden3:
    distribution: uniform
    min: 3
    max: 10
  hidden4:
    distribution: uniform
    min: 3
    max: 10
  latent_input_dim:
    values: [4, 5, 6, 7, 8, 9]
  lr:
    values: [-5, -4, -3, -2, -1, 0]