program: train.py
method: bayes
metric:
  goal: maximize
  name: correlation
parameters:
  dropout:
    values: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  hidden1:
    values: [16, 32, 64, 128, 256, 512]
  hidden2:
    values: [16, 32, 64, 128, 256, 512]
  hidden3:
    values: [16, 32, 64, 128, 256, 512]
  latent_input_dim:
    values: [16, 32, 64, 128, 256, 512, 1024]
  lr:
    values: [1e-2, 5e-2, 1e-1, 5e-1, 1, 5, 10]