program: main.py
method: bayes
metric:
  goal: maximize
  name: best_correlation
parameters:
  hidden1:
    distribution: uniform
    min: 3.5
    max: 9.5
  hidden2:
    distribution: uniform
    min: 3.5
    max: 9.5
  hidden3:
    distribution: uniform
    min: 3.5
    max: 9.5
  lr:
    values: [1e-5, 1e-4, 1e-3, 1e-2, 1e-1]