program: train.py
method: bayse
metric:
  goal: maximum
  name: correlation
parameters:
  hidden2:
    values: [4, 8, 16, 32, 64, 128, 256, 512, 1024]
  dropout1:
    values: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  hidden2:
    values: [4, 8, 16, 32, 64, 128, 256, 512, 1024]
  dropout2:
    values: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
# early_terminate:
#   type: hyperband
#   s: 2
#   eta: 3
#   max_iter: 27