seed: 77
wandb: True
wandb_project: kaggle_MSCI_multi
phase: multi

fold: GroupKFold
group: donor
n_folds: 3
use_fold: [0, 1, 2]
device: 'cuda:0'
output_size: 23418

n_epochs: 30

loss: correlation

optimizer: AdamW
lr: 1e-3
weight_decay: 1e-2

scheduler: None
T_0: ${n_epochs} # CAWR
T_mult: 1 # CAWR
eta_min: 1e-9 # CAWR

pct_start: 0.1 # OCLR
div_factor: 25. # OCLR
final_div_factor: 1000. # OCLR

train_bs: 512
valid_bs: 512
test_bs: 512

